---
jobs: 10
cluster: "sbatch -A fmlab -p general -t {resources.time_min} --mem={resources.mem_mb} -n 1 -c {resources.cpus} -o logs/{rule}_{wildcards} -e logs/{rule}_{wildcards}"
default-resources: [cpus=1, mem_mb=8000, time_min=60]
