# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samplesheet: "sample_sheet.tsv"
rds: "/mnt/scratcha/fmlab/smith10/focal/britroc_30kb_ds_absCopyNumber.rds"
meta: "/mnt/scratcha/fmlab/smith10/focal/britroc_30kb_signature_data_meta.tsv"
output_dir: "/mnt/scratcha/fmlab/smith10/focal/"
gistic: "./"
